name: CI/CD to GitHub

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  laravel-tests:
    name: Run Laravel Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: mbstring, pdo, bcmath
          ini-values: post_max_size=256M, upload_max_filesize=256M
          coverage: none

      - name: Install Dependencies
        run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader

      - name: Set Up Environment
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Run Migrations
        run: php artisan migrate --force --seed

      - name: Run Tests
        run: php artisan test

  sync-back:
    name: Push Changes Back to GitHub
    runs-on: ubuntu-latest
    needs: laravel-tests
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set GitHub User Details
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Sync Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add .
